[package]
name = "quercus_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "quercus_derive"
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = { version = "1.0.105", features = ["extra-traits"] }
